# These are supported funding model platforms

github: [sparshsam]
# patreon: # Uncomment to enable
# open_collective: # Uncomment to enable
# ko_fi: # Uncomment to enable
# tidelift: # Uncomment to enable
# community_bridge: # Uncomment to enable
# liberapay: # Uncomment to enable
# issuehunt: # Uncomment to enable
# otechie: # Uncomment to enable
# custom: # Uncomment to enable
